---
# Simple Codemagic configuration for PersianAIAssistant

workflows:
  android-build:
    name: Build Android App
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      java: 17
      vars:
        # Add your environment variables here if needed
        # EXAMPLE_VAR: "example_value"
    
    scripts:
      - name: Build Debug APK
        script: |
          echo "Starting Android build..."
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
          echo "Build completed successfully!"
    
    artifacts:
      - app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
