---
# Codemagic configuration for PersianAIAssistant
# Written for Codemagic 2.0 workflow format

workflows:
  android-workflow:
    name: Android Build Pipeline
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      java: 17
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    
    scripts:
      - name: Set up build environment
        script: |
          echo "Setting up build environment..."
          chmod +x gradlew
          ./gradlew --version
      
      - name: Clean project
        script: |
          echo "Cleaning project..."
          ./gradlew clean
      
      - name: Build Debug APK
        script: |
          echo "Building debug APK..."
          ./gradlew assembleDebug --stacktrace --info
          echo "Debug build completed"
      
      - name: Build Release APK (if keystore is available)
        script: |
          echo "Skipping release build - no keystore configured"
          echo "To enable release builds, configure keystore in Codemagic settings"
      
      - name: Generate build report
        script: |
          echo "Generating build report..."
          find app/build/outputs -name "*.apk" -exec ls -lh {} \; > build_report.txt
          cat build_report.txt
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - build.log
      - build_report.txt
      - app/build/reports/**/*
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  # Additional workflow for testing
  android-test:
    name: Android Test Pipeline
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      java: 17
    
    scripts:
      - name: Run unit tests
        script: |
          echo "Running unit tests..."
          ./gradlew testDebugUnitTest
      
      - name: Run lint checks
        script: |
          echo "Running lint checks..."
          ./gradlew lintDebug
    
    artifacts:
      - app/build/reports/tests/**/*
      - app/build/reports/lint-results*.*
