workflows:
  android-workflow:
    name: Android Build (Debug)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.persianai.assistant"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set up Gradle wrapper
        script: |
          gradle wrapper --gradle-version 8.2
      - name: Grant execute permission
        script: |
          chmod +x gradlew
      - name: Get dependencies
        script: |
          ./gradlew dependencies --no-daemon
      - name: Build Android Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ghadirb@example.com
        notify:
          success: true
          failure: true
      scripts:
        - name: Success notification
          script: |
            echo "✅ Debug APK build completed successfully!"
            echo "📦 APK location: app/build/outputs/apk/debug/app-debug.apk"
