workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --info 2>&1 | tee build.log
          echo "Build completed with exit code: $?"
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@gmail.com
